export const projectsData = [
  {
    id: 1,
    title: "AI-Powered Portfolio",
    category: "Web App",
    image: "https://images.unsplash.com/photo-1555066931-4365d14bab8c?w=800",
    techStack: ["React 19", "Three.js", "OpenAI API", "Tailwind CSS", "Framer Motion"],
    description: "An immersive 3D portfolio website with AI assistant, interactive terminal, and real-time GitHub analytics. Features cinematic animations and holographic UI elements.",
    aiSummary: "This project demonstrates cutting-edge web technologies combining AI with immersive 3D experiences. The AI assistant provides context-aware responses about my work, while the terminal offers an interactive way to explore my profile. Built with React 19 and Three.js for optimal performance and visual appeal.",
    architecture: "Frontend: React 19 with Vite for fast builds. 3D: Three.js with React Three Fiber for efficient rendering. AI: OpenAI GPT-4 integration for intelligent responses. State: Zustand for global state management. Animations: GSAP and Framer Motion for smooth transitions.",
    keyFeatures: [
      "Cinematic 3D hero section with floating geometries",
      "AI-powered assistant with natural language processing",
      "Interactive developer terminal with 15+ commands",
      "Real-time GitHub analytics dashboard",
      "Custom cursor with magnetic interactions",
      "Fully responsive with mobile optimization"
    ],
    complexity: "Advanced",
    challenges: "Optimizing 3D performance across devices, implementing real-time AI responses, creating smooth scroll-based animations without lag.",
    solutions: "Implemented adaptive quality settings based on FPS, used React Query for caching, and optimized shaders for better GPU performance.",
    githubLink: "https://github.com/manishkumar/ai-portfolio",
    liveLink: "https://manishkumar.dev",
    date: "2024",
    stars: 234,
    forks: 56
  },
  {
    id: 2,
    title: "Neural Style Transfer",
    category: "AI/ML",
    image: "https://images.unsplash.com/photo-1620712943543-bcc4688e7485?w=800",
    techStack: ["Python", "TensorFlow", "React", "Flask", "OpenCV"],
    description: "Real-time artistic style transfer using deep neural networks. Transform any image into artwork inspired by famous artists.",
    aiSummary: "This deep learning project implements neural style transfer algorithms to blend content and style images. Using VGG19 architecture, it extracts feature representations and applies artistic styles in real-time. The model achieves high-quality results with optimized inference time.",
    architecture: "Backend: Flask API serving TensorFlow models. Frontend: React for image upload and preview. Model: Pre-trained VGG19 with custom loss functions. Optimization: Model pruning and quantization for faster inference.",
    keyFeatures: [
      "Real-time style transfer in under 3 seconds",
      "Support for 20+ artistic styles",
      "Batch processing for multiple images",
      "High-resolution output (up to 4K)",
      "Style intensity adjustment",
      "Before/after comparison slider"
    ],
    complexity: "Expert",
    challenges: "Balancing style transfer quality with speed, handling large image sizes, implementing efficient GPU utilization.",
    solutions: "Used progressive resizing technique, implemented caching mechanism, and optimized model with TensorFlow Lite.",
    githubLink: "https://github.com/manishkumar/neural-style-transfer",
    liveLink: "https://style-transfer.manishkumar.dev",
    date: "2024",
    stars: 456,
    forks: 89
  },
  {
    id: 3,
    title: "Predictive Analytics Dashboard",
    category: "Data Science",
    image: "https://images.unsplash.com/photo-1551288049-bebda4e38f71?w=800",
    techStack: ["Python", "Scikit-learn", "Django", "D3.js", "PostgreSQL"],
    description: "ML-powered sales forecasting platform with real-time analytics and interactive visualizations.",
    aiSummary: "A comprehensive business intelligence platform that uses machine learning to forecast sales trends. The system analyzes historical data, seasonality patterns, and external factors to predict future sales with 95% accuracy. Features include interactive dashboards and automated report generation.",
    architecture: "Data Pipeline: Apache Airflow for ETL. ML Models: Ensemble methods (Random Forest, XGBoost). Backend: Django REST API. Frontend: React with D3.js for visualizations. Database: PostgreSQL with TimescaleDB for time-series data.",
    keyFeatures: [
      "95% accurate 30-day sales forecasts",
      "Real-time data processing and updates",
      "Interactive charts with drill-down capability",
      "Automated weekly report generation",
      "Multi-tenant support for different business units",
      "Export to PDF/Excel functionality"
    ],
    complexity: "Advanced",
    challenges: "Handling missing data and outliers, selecting optimal forecasting models, scaling for large datasets.",
    solutions: "Implemented data imputation techniques, used ensemble methods for robustness, deployed on AWS with auto-scaling.",
    githubLink: "https://github.com/manishkumar/predictive-analytics",
    liveLink: "https://analytics.manishkumar.dev",
    date: "2023",
    stars: 178,
    forks: 34
  },
  {
    id: 4,
    title: "3D Product Configurator",
    category: "3D Web",
    image: "https://images.unsplash.com/photo-1581092335874-5c5c6f6b4c8f?w=800",
    techStack: ["Three.js", "React", "Node.js", "WebGL", "Blender"],
    description: "Real-time 3D product customization tool for e-commerce platforms with photorealistic rendering.",
    aiSummary: "This interactive 3D configurator allows customers to customize products in real-time with photorealistic rendering. Features include color/material changes, texture mapping, and real-time lighting adjustments. Built with Three.js and optimized for web performance.",
    architecture: "3D Engine: Custom Three.js implementation. Asset Pipeline: GLTF/GLB models optimized with Draco compression. Backend: Node.js for asset management. State Management: Redux for configuration state. Rendering: WebGL with post-processing effects.",
    keyFeatures: [
      "Real-time product customization",
      "Photorealistic rendering with PBR materials",
      "360° product viewing",
      "Multiple lighting presets",
      "High-resolution screenshot capture",
      "Share configuration via URL"
    ],
    complexity: "Advanced",
    challenges: "Optimizing 3D models for web, achieving smooth performance on mobile, implementing realistic materials.",
    solutions: "Used model optimization techniques (LOD, mesh simplification), implemented WebGL worker for rendering, used compressed textures.",
    githubLink: "https://github.com/manishkumar/3d-configurator",
    liveLink: "https://configurator.manishkumar.dev",
    date: "2023",
    stars: 312,
    forks: 67
  },
  {
    id: 5,
    title: "Sentiment Analysis Chatbot",
    category: "AI/ML",
    image: "https://images.unsplash.com/photo-1531746790731-6c087fecd65a?w=800",
    techStack: ["Python", "NLTK", "Flask", "Socket.io", "React"],
    description: "Intelligent chatbot with emotion detection and sentiment analysis for customer support automation.",
    aiSummary: "An AI-powered chatbot that understands user emotions and responds accordingly. Uses NLP techniques for sentiment analysis and intent recognition. Integrated with business systems for automated customer support and lead generation.",
    architecture: "NLP Pipeline: SpaCy for entity recognition, NLTK for sentiment analysis. Model: LSTM for intent classification. Backend: Flask-SocketIO for real-time communication. Frontend: React with chat interface. Database: MongoDB for conversation history.",
    keyFeatures: [
      "Real-time sentiment and emotion detection",
      "Multi-language support (English, Spanish, Hindi)",
      "Context-aware conversations",
      "Automated ticket creation for negative sentiment",
      "Analytics dashboard for sentiment trends",
      "REST API for integration"
    ],
    complexity: "Advanced",
    challenges: "Accurate emotion detection across languages, handling ambiguous queries, maintaining conversation context.",
    solutions: "Used ensemble of NLP models, implemented context window mechanism, trained custom models on industry-specific data.",
    githubLink: "https://github.com/manishkumar/sentiment-chatbot",
    liveLink: "https://chatbot.manishkumar.dev",
    date: "2023",
    stars: 104,
    forks: 23
  },
  {
    id: 6,
    title: "AR Try-On Experience",
    category: "AR/VR",
    image: "https://images.unsplash.com/photo-1572635196237-14b3f281503f?w=800",
    techStack: ["WebXR", "Three.js", "TensorFlow.js", "MediaPipe", "React"],
    description: "Augmented reality virtual try-on for eyewear and accessories using real-time face tracking.",
    aiSummary: "Innovative AR solution using WebXR and TensorFlow.js for real-time face detection and product placement. Allows customers to try products virtually before purchase. Achieves 60fps performance on modern browsers without additional hardware.",
    architecture: "Face Detection: MediaPipe for landmark detection. Rendering: Three.js with WebXR support. Tracking: Custom Kalman filter for smooth tracking. Backend: Node.js for product management. Frontend: React with camera integration.",
    keyFeatures: [
      "Real-time face detection and tracking",
      "Virtual product placement with accurate scaling",
      "Multiple product categories (eyewear, jewelry, makeup)",
      "Screenshot and share functionality",
      "Product comparison tool",
      "Color and style variations"
    ],
    complexity: "Expert",
    challenges: "Accurate face tracking in varying lighting, smooth AR rendering, maintaining stable frame rates.",
    solutions: "Used MediaPipe for robust face detection, optimized shaders for WebGL, implemented adaptive quality settings.",
    githubLink: "https://github.com/manishkumar/ar-tryon",
    liveLink: "https://artryon.manishkumar.dev",
    date: "2024",
    stars: 289,
    forks: 45
  }
]